role: slice
jid: integration@rd00.engineyard.com
password: testing
use_drb: true
drb_port: 10393
debug: false
jabber_debug: true
herault_jid: herault@rd00.engineyard.com/herault
actors:
 - vertebra-gemtool/actor
default_resources:
 - /client
log_path: /tmp/ey_client.log
pid_path: /tmp/ey_client.pid
